---
- name: "update local apt repo."
  become: true
  apt:
    update_cache: yes

- name: "upgrade apt packages"
  become: true
  apt:
    upgrade: yes

- name: "remove stale dependencies"
  become: true
  apt:
    autoremove: yes

- name: "install dependencies [nodejs and npm]."
  become: true
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: "Copy artifact into Instance" 
  become: true
  copy:
    src: ~/project/artifact.tar.gz
    dest: /home/ubuntu/artifact.tar.gz

- name: "Extract artifact"
  become: true
  shell: |
    cd /home/ubuntu
    tar xzvf artifact.tar.gz

- name: "Build and Start app"
  become: true
  shell: |
    cd /home/ubuntu
    npm i
    npm run build
    pm2 stop all
    pm2 start npm -- start